### PR TITLE
Use set for checking types

### PR DESCRIPTION
**Pull request by laike9m**
Replaced tuple with set to make the `in` operation faster.

### CODE REVIEW

**Comment by davvid** [comment]
Thanks!

**Comment by laike9m** [comment]
Is it possible to release a new version?

**Comment by davvid** [comment]
`jsonpickle==1.4.2` should be available via pypi now.  cheers

**Comment by laike9m** [comment]
Nice, thanks for the work!

**Comment by davvid** [comment]
I should also mention that a fix for #235 was just committed.  Please not that this change was *not* included in 1.4.2 since it was hot off the presses.  I plan to tag a release with that fix before the end of the year, but please shout out if it would be helpful sooner rather than later.

cheers!

**Comment by laike9m** [comment]
Got it, no worries

**Pull request merged**
