### PR TITLE
Correct issue 117

### PR DESCRIPTION
**Pull request by jaraco**
I believe I've distilled, captured, and corrected the failure identified in Issue #117. Please review and make a bugfix release as soon as possible. Thanks.

### CODE REVIEW

**Comment by marcintustin** [comment]
LGTM. @davvid

**Comment by davvid** [comment]
Nice catch, thanks :+1:

**Comment by jaraco** [comment]
Glad to help. Any chance of a release of this fix?

**Comment by davvid** [comment]
7a0bc58b209571439ea065f48faf6f043866fec0 tagged as `v0.9.1`

**Pull request merged**
