### PR TITLE
I ran into some problems which I detailed in issue #99

### PR DESCRIPTION
**Pull request by lkrubner**
I ran into some problems which I detailed in issue 99, https://github.com/jsonpickle/jsonpickle/issues/99. I was pulling models out of SqlAlchemy and some of the sub-classes were not iterable, so I went through and added if/else blocks where I was facing problems. This now works for me, without any obvious errors.

### CODE REVIEW

**Comment by abhijeetkalyan** [comment]
Hi, just wondering what the status of this PR was. Having the same issue as @lkrubner

**Comment by lkrubner** [comment]
I am sorry I only noticed your comments now. I don't often work with Python, so I only catch up on Python projects maybe once a year. I am sorry to say I no longer have the original problem in front of me. But I recall this line gave me several errors: 

       if rv_as_list[0].__name__ == '__newobj__':

And so the only way I could get this to work was wrapping it with: 

      if hasattr(rv_as_list[0], __name__):

**Comment by davvid** [comment]
I'd like to see this expressed in a unit test form. Can you please share a snippet that we can keep around in the test suite for validating this use case and potential fix? The best part is that if we have a sufficiently elaborate test case then you can be sure that we won't ever break your use case in the future.

The `str(...)` casts also caught my attention -- it made me wonder about `float` and `int` fields, so I'm curious to get a good test case for this.  Keeping sqlalchemy-related tests in the test suite is fine with me. When testing we can use a `sqlite:///:memory:` url to allow the tests to not rely on the filesystem.

**Comment by davvid** [comment]
I added sqlalchemy tests to our test suite so I went ahead and closed this issue.  The tests in `tests/sqlalchemy_test.py` are basically what we can currently support.

The tests that were added may be overly simplistic. If you're able to demonstrate a breakage please try to do it by adding new tests to `tests/sqlalchemy_test.py` so that we can have a common baseline to work against.

Thanks again for the report. Let us know if there's anything more we should add to the existing tests that would help your use case.

**Pull request closed without merging**
