### PR TITLE
Update pandas.py

### PR DESCRIPTION
**Pull request by antoinecollet5**
Makes it compatible with multi-level columns Pandas DataFrame.
The trick is to use the keyword `header` from `pandas.read_csv` to indicate how many rows of the `csv` file to take into account for the columns creation.
The names of the levels are also stored and reassigned after the df has been created.

### CODE REVIEW

**Comment by Theelgirl** [comment]
Just want to make it clear for any maintainers coming along that according to travis, the tests that this fails are only flake8 and black tests, not compatibility tests, so the "errors" could be fixed with a simple flake8 and black runthrough.

**Comment by davvid** [comment]
Thank you @Theelgirl and @antoinecollet5  -- I'll tag the repo now and start merging this down as the next round of topics for the next release.  Since these are "just" formatting issues I'll fix that up locally.  Cheers!

**Comment by davvid** [comment]
There is one test failure where this change dropped support for timedelta columns.  I'm restoring that functionality now; it's a simple fix.

I'll also be adding a unit test that exercises the issue described in #346 so that we don't regress on this enhancement in the future.

**Comment by davvid** [comment]
I merged this in after adding a unit test that verifies the behavior.

There are a few remaining issues.  It looks like this functionality requires that the `ujson` module is available.  I hadn't noticed because the virtualenvs I use for testing all had it available.  I tweaked the requirements-dev.txt to reflect that fact that ujson is available for all python versions now.

This also led me to realize that, indeed, the tests do fail when numpy 1.20.0 is installed, as reported in #336.

The setup.cfg file is currently locked down to numpy 1.19 for now, but this would be great to improve.  Likewise, it would be a good idea to make this new feature not require ujson.

The root cause seems to be that this feature relies on sticking tuples in dictionary keys.  While we do support that in jsonpickle, the flatten process shouldn't leave that around since it will cause issues since it's non-standard json.  It's the dtypes dict that ends up containing tuples which is what makes it go sideways.  I'll be looking into resolving this one.

The numpy ujson settings in `setup.cfg` will have to be tweaked (and your `.tox` directory purged) in order to see the numpy 1.20 failures.. it's currently locked down to 1.19.4.

**Comment by davvid** [comment]
Alrighty, I was able to eliminate the ujson oversight by ensuring that the `dtypes` value in the meta dict is now flattened before handling off to the backend.  Please see 39a6cbed3b9d99b9d3ce560eed44a2c10e1e9136 for the small tweak that made that possible.

Thanks again!

**Comment by antoinecollet5** [comment]
Thank you @davvid ! Cheers

**Pull request closed without merging**
