### PR TITLE
Proper bytestring support + numpy extension

### PR DESCRIPTION
**Pull request by aldanor**
This adds support for bytestring encoding/decoding as discussed in #108, plus numpy support with some tests.

I don't think the unicode/bytes change is bound to break much since
- unicode strings in both Python 2/3 are encoded and decoded same as before, via json literals; in addition, unicode in always means unicode out
- encoding of bytestrings that are not decodable into utf-8 in Python 2 were failing anyway (downstream in the backend code, for most or all backends), so there's nothing to break there
- the most significant change is proper encoding of Python 3 bytestrings -- but then again, (a) Python 3 makes a hard distinction between bytes/unicode so the chances are one would know what he's doing if using them, (b) trying to encode a bytestring in py3 as of the current master would raise a recursion limit exception (#101, #108) so noone would be possibly doing that

The reason for having unicode as default and bytes as a special case (and not the other way around as suggested in #13) is that (a) the default text type in Python 3 is unicode, and bytes is a essentially a binary type, (b) bytestrings natively pickled in Python 2 are decoded as unicode in Python 3, by design.

The only thing that's lacking is being able to force encoding ascii bytestrings as true bytestrings in Python 2, but I don't see an easy way to do this without overcomplicating the whole thing.

There may still be a few things to add or polish but I wanted to open a PR early for @davvid and @marcintustin to take a look. For one thing, there need to be additional tests for the whole bytes/unicode logic (edit: *done*). Maybe some additional numpy tests as well to verify the encoding format explicitly and not only the roundtrip.

On a sidenote, `jsonpickleJS` would probably need to be updated as well to be aware of `py/bytes` and `quopri` encoding.

### CODE REVIEW

**Comment by aldanor** [comment]
Related: #101, #108.

**Comment by davvid** [comment]
The code is good but after merging the tests fail because of doctests:

```
$ ./tests/runtests.py
----------------------------------------------------------------------
File "jsonpickle/pickler.py", line 118, in jsonpickle.pickler.Pickler.flatten
Failed example:
    p.flatten('hello world')
Expected:
    'hello world'
Got:
    u'hello world'
----------------------------------------------------------------------
File "jsonpickle/pickler.py", line 137, in jsonpickle.pickler.Pickler.flatten
Failed example:
    p.flatten({'key': 'value'})
Expected:
    {'key': 'value'}
Got:
    {'key': u'value'}
```

I remember these docstrings. I've had to fix them before when porting to python3, and I'm pretty sure fixing them for py2 breaks py32, py33 or something.  IMO these two docstrings have been too high maintenance and are better off removed.  Want to do the honors?

**Comment by aldanor** [comment]
Tests work in tox for me locally and they work on travis, strange. What interpreter version are you running them from, wonder what exactly is different

Re: doctests,

**Comment by aldanor** [comment]
Oh, ok, I see -- fails for me as well.

**Pull request merged**
