### PR TITLE
Minor speedup for _get_flattener on complex objects

### PR DESCRIPTION
**Pull request by Theelgirl**
Sped up _get_flattener (part of the Pickler) by merging the tuple and set checks. Performance increases most notably if encoding many tuples, sets, or other non-list/dict objects.

### CODE REVIEW

**Comment by Theelgirl** [comment]
Don't merge just yet -- more improvements coming. I should have made this a draft pull request, sorry.

**Comment by Theelgirl** [comment]
Ok, I think that's all. It's ready to merge once checks are completed with travis.

**Comment by Theelgirl** [comment]
Sorry I'm really bad with git. Or any workflow tool to be honest, coding is more of a hobby for me lmao.

**Comment by davvid** [comment]
It's all good, I don't mind seeing your works-in-progress.

What platform are you on?  If you need a recommendation for a nice git gui which might help with visualizing your edits, [I won't be shy about recommending the best one around](https://github.com/git-cola/git-cola). 😄 

I would suggest doing a rebase after you've got it all nice and committed, but you can always save that stuff for the end.  Rebasing will let you pick up stuff that's been pushed upstream.  (sorry, you probably already know that)

...

I like to joke that my "2nd gig" is a "git trainer" since everyone tends to come to me with their git questions, so I tend go into "git helper mode" when someone says they're not familiar with git.  I'm happy to help if you have any questions.

**Comment by Theelgirl** [comment]
Actually, I had no clue what rebasing was, so thanks! I'll try out git cola, meanwhile this is all ready for merging.

**Comment by Theelgirl** [comment]
@davvid Can this get merged?

**Pull request merged**
